Fail nicer when the specified root family doesn't exist
Sample output:

	Exception: Root family 'F1' is not found. First valid family would be '41'.

Related to <https://github.com/vmiklos/ged2dot/issues/201>.

Change-Id: I06ef7898e8306361bfe883fe7d926ed2ce8e3379